let appConstants = {
    VALUE_OF_MIN_IN_SEC : 60,
	VALUE_OF_HOUR_IN_MIN : 60,
	ALLOWED_LOWER_MPH : 5,
	ALLOWED_UPPER_MPH : 100,
	DEFAULT_TIME_FOR_TRIP : 0,	
	DRIVER_COMMAND : "Driver",
    TRIP_COMMAND : "Trip",
    DRIVER_COMMAND_LENGTH : 2,
    TRIP_COMMAND_LENGTH : 5,
    COMMAND_SEPARATOR : " ",
    TIME_SEPARATOR : ":"
};

module.exports = appConstants;